version: '3.0'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    extra_hosts:
      - "docker_host:176.187.142.148"
    command:
        --default-authentication-plugin=mysql_native_password
        --max_connections=666
        --bind-address=0.0.0.0
        --transaction-isolation=READ-COMMITTED
    environment:
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_USER=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_HOST=%
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_LOCAL_PORT
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

  magicpark-api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file: ./.env
    container_name: magicpark-api
    restart: unless-stopped
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS="./src/main/resources/service-account-file.json"
      - MYSQL_HOST=$MYSQLDB_HOST
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PORT=$MYSQLDB_PORT
      - SERVER_PORT=$API_LOCAL_PORT
    ports:
      - $API_PORT:$API_LOCAL_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
